project:
  type: website
  output-dir: docs

website:
  title: "CPs"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: The project
        menu:
        - project_description.qmd
      
      - text: Blog posts
        file: dissemination.qmd
      
      - text: Introductions and Tutorials
        menu:
        - introductions.qmd
        - tutorials.qmd
        
      - text: About the team
        file: about_the_team.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

